name: help_scout_flutter
version: 0.0.1

description: | 
  A new Flutter plugin for the implementation of HelpScout Beacon.
homepage: https://github.com/bhusal-dip/help_scout_flutter

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: any

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: HelpScoutFlutterPlugin

